package org.freakz.hokan_ng_springboot.bot.enums;

/**
 * Created by Petri Airio on 17.11.2015.
 * -
 */
public enum ServiceMessageType {

    CATCH_URLS_REQUEST,
    CURRENCY_CONVERT_REQUEST,
    CURRENCY_LIST_REQUEST,
    HORO_REQUEST,
    METAR_REQUEST,
    NIMIPAIVA_DAY_REQUEST,
    NIMIPAIVA_NAME_REQUEST,
    TV_DAY_REQUEST,
    TV_FIND_REQUEST,
    TV_INFO_REQUEST,
    TV_NOW_REQUEST,
    TRANSLATE_REQUEST,
    UPDATERS_LIST_REQUEST,
    UPDATERS_START_REQUEST,
    WEATHER_REQUEST

}
